f = open("show.txt",mode="r",encoding="utf-8")
print("file name:",f.name)
print("file mode:",f.mode)
print("file readable:",f.readable())
print("file writable:",f.writable())
print("file closed:",f.closed)
f.close()
print("file close:",f.closed)